title: Nolan's Blog
description: "Class of 2025"
owner_name: Nolan Hightower
github_username: nulxn
github_repo: "nolan_2025"
baseurl: "/nolan_2025"
future: true

# Uncomment the remote_theme line for the desired theme
#remote_theme: pages-themes/cayman@v0.2.0
remote_theme: andrewhwanpark/dark-poole
#remote_theme: jekyll/minima
#remote_theme:pages-themes/midnight@v0.2.0

minima:
  skin: dark
  social_links:
    - { platform: github, user_url: "https://github.com/nighthawkcoders" }
    - { platform: x, user_url: "https://x.com/NighthawkCoding/" }
    - {
        platform: youtube,
        user_url: "https://www.youtube.com/@nighthawkcodingsociety2868",
      }

plugins:
  - jekyll-remote-theme

header_pages:
  - navigation/blog.md
  - navigation/search.md
  - navigation/about.md
  - navigation/gallery.md
  - README4YML.md
